millwright_menu:
    renderers:
        navigation: #menu type id
            renderer: null # custom renderer
            rendererOptions:
                template: MillwrightMenuBundle:Default:knp_menu.html.twig
                ancestorClass: current active
                currentClass: current_item

    items: #menu items
        d_service:
            label: 'ТК'
        delivery_service:
            label: 'Транспортные компании'
            route:  Nitra_DeliveryBundle_Delivery_list
        department:
            label:  'Отделения ТК'
            route:  Nitra_DeliveryBundle_Department_list
        delivery_city:
            label:  'Города в ТК'
            route:  Nitra_DeliveryBundle_DeliveryCity_list
        territory:
            label:  'Территории'
        region:
            label:  'Регионы'
            route:  Nitra_GeoBundle_Region_list
        city:
            label:  'Города'
            route:   Nitra_GeoBundle_City_list
        client: 
          label:  'Клиенты'
        client_list:
          label:    'Список клиентов'
          route:  Nitra_DeliveryBundle_Client_list
        managers:
          label:   'Менеджеры'
          route:  Nitra_ManagerBundle_Manager_list
        settings:
          label:  'Настройки'
        groups:
          label:  'Группы'
          route:  Nitra_ManagerBundle_Group_list
        roles:
          label:   'Привилегии'
          route:  Nitra_ManagerBundle_Role_list
        
    tree: #menu containers
        main: #main container
            type: navigation # menu type id
            children:
                d_service:
                  children:
                    delivery_service:    ~
                    department:    ~
                    delivery_city:    ~
                territory:
                  children:
                    region:    ~
                    city:    ~
                client:
                  children:
                    client_list:  ~
                    managers:  ~
                settings:
                  children:
                    groups:  ~
                    roles:  ~
                  