millwright_menu:
    renderers:
        navigation: #menu type id
            renderer: null # custom renderer
            rendererOptions:
                template: MillwrightMenuBundle:Default:knp_menu.html.twig
                ancestorClass: current active
                currentClass: current_item

    items: #menu items        
        
        delivery:
            label:  "ТК"
            
        delivery_tk:
            label:  "Все ТК"
            route:  Nitra_DeliveryBundle_Delivery_list
            
        delivery_city:
            label:  "Города ТК"
            route:  Nitra_DeliveryBundle_City_list
            
        delivery_warehouse:
            label:  "Склады ТК"
            route:  Nitra_DeliveryBundle_Warehouse_list
            
        delivery_client:
            label:  "Клиенты"
            route:  Nitra_DeliveryBundle_Client_list
            
        manager:
            label:  "Пользователи"
            
        manager_list:
            label:  "Менеджеры"
            route:  Nitra_ManagerBundle_Manager_list
            
        catalog: 
            label:  "Справочники"
            
        geo_country:
            label:  "Страны"
            route:  Nitra_GeoBundle_Country_list
            
        geo_region:
            label:  "Регионы"
            route:  Nitra_GeoBundle_Region_list
            
        geo_city:
            label:  "Города"
            route:  Nitra_GeoBundle_City_list
        
#        # Фикстуры эталона GeoBundle
#        geo_fixtures:
#            label:  "GeoBundle:Фикстуры"
#            
#        geo_fixtures_country:
#            label:  "Fixtures:Страны"
#            route:  Nitra_GeoBundle_Fixtures_country
#            
#        geo_fixtures_region:
#            label:  "Fixtures:Регионы"
#            route:  Nitra_GeoBundle_Fixtures_region
#            
#        geo_fixtures_city:
#            label:  "Fixtures:Города"
#            route:  Nitra_GeoBundle_Fixtures_city

    tree: #menu containers
        main: #main container
            type: navigation # menu type id
            children:
                    
                delivery:
                    name:   "ТК"
                    children:
                        delivery_tk:            ~
                        delivery_city:          ~
                        delivery_warehouse:     ~
                    
                manager:
                    name:   "Пользователи"
                    children:
                        delivery_client:    ~
                        manager_list:       ~
                    
                catalog:
                    name:   "Справочники"
                    type:   navigation
                    children:
                        geo_country:    ~
                        geo_region:     ~
                        geo_city:       ~
                        
#                geo_fixtures:
#                    name:   "GeoBundle:Фикстуры"
#                    type:   navigation
#                    children:
#                        geo_fixtures_country:   ~
#                        geo_fixtures_region:    ~
#                        geo_fixtures_city:      ~

