Default_route:
  pattern: "/"
  defaults: { _controller: NitraDeliveryBundle:Delivery/List:index }
  
NitraManagerBundle_admin_nitra_manager_bundle_Group:
    resource: "@NitraManagerBundle/Controller/Group/"
    type:     admingenerator
    prefix:   /group

NitraManagerBundle_admin_nitra_manager_bundle_Role:
    resource: "@NitraManagerBundle/Controller/Role/"
    type:     admingenerator
    prefix:   /role

Nitra_DeliveryBundle_Client_newToken:
    resource: "@NitraDeliveryBundle/Controller/Client"
    type:     annotation
    prefix:   /client
    
NitraDeliveryBundle_Synchronization_Delivery_Period:
  pattern:  /sync-delivery-period/{key}/{cityFrom}/{cityTo}
  defaults:  { _controller: NitraDeliveryBundle:Sync:syncDeliveryPeriod }

NitraDeliveryBundle_Synchronization:
  pattern:  /sync/{key}
  defaults:  { _controller: NitraDeliveryBundle:Sync:synchronization }

NitraGeoBundle_Synchronization:
  pattern:  /geo-sync/{key}
  defaults:  { _controller: NitraGeoBundle:GeoSync:synchronization }
  
NitraGeoBundle_Synchronization_Region:
  pattern:  /geo-sync-region/{key}
  defaults:  { _controller: NitraGeoBundle:GeoSync:synchronizationRegion }

NitraGeoBundle_Synchronization_City:
  pattern:  /geo-sync-city/{key}
  defaults:  { _controller: NitraGeoBundle:GeoSync:synchronizationCity }
  
NitraGeoBundle_Synchronization_Country:
  pattern:  /geo-sync-country/{key}
  defaults:  { _controller: NitraGeoBundle:GeoSync:synchronizationCountry }

#NitraDeliveryBundle_geographi:
#  pattern:  /geographi
#  defaults:  { _controller: NitraDeliveryBundle:Sync:geographi }
  
NitraDeliveryBundle_warehousePek:
  pattern:  /warehouse-pek
  defaults:  { _controller: NitraDeliveryBundle:Sync:warehousePek }

NitraDeliveryBundle_admin_nitra_delivery_bundle_Client:
    resource: "@NitraDeliveryBundle/Controller/Client/"
    type:     admingenerator
    prefix:   /client

NitraDeliveryBundle_admin_nitra_delivery_bundle_Department:
    resource: "@NitraDeliveryBundle/Controller/Department/"
    type:     admingenerator
    prefix:   /department

NitraDeliveryBundle_admin_nitra_delivery_bundle_DeliveryCity:
    resource: "@NitraDeliveryBundle/Controller/DeliveryCity/"
    type:     admingenerator
    prefix:   /delivery-city

NitraDeliveryBundle_admin_nitra_delivery_bundle_DeliveryCity_annotation:
    resource: "@NitraDeliveryBundle/Controller/DeliveryCity/"
    type:     annotation
    prefix:   /delivery-city

NitraDeliveryBundle_admin_nitra_delivery_bundle_Delivery:
    resource: "@NitraDeliveryBundle/Controller/Delivery/"
    type:     admingenerator
    prefix:   /delivery

NitraManagerBundle:
    resource: "@NitraManagerBundle/Resources/config/routing.yml"
    prefix:   /
    
NitraGeoBundle:
    resource: "@NitraGeoBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

