<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131209175430 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_region DROP FOREIGN KEY FK_A4B3C808896DBBDE");
        $this->addSql("ALTER TABLE geo_region DROP FOREIGN KEY FK_A4B3C808B03A8386");
        $this->addSql("DROP INDEX IDX_A4B3C808B03A8386 ON geo_region");
        $this->addSql("DROP INDEX IDX_A4B3C808896DBBDE ON geo_region");
        $this->addSql("ALTER TABLE geo_region DROP updated_by_id, DROP created_by_id");
        $this->addSql("ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34896DBBDE");
        $this->addSql("ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34B03A8386");
        $this->addSql("DROP INDEX IDX_297C2D34B03A8386 ON geo_city");
        $this->addSql("DROP INDEX IDX_297C2D34896DBBDE ON geo_city");
        $this->addSql("ALTER TABLE geo_city DROP updated_by_id, DROP created_by_id");
        $this->addSql("ALTER TABLE geo_country DROP FOREIGN KEY FK_E4654464896DBBDE");
        $this->addSql("ALTER TABLE geo_country DROP FOREIGN KEY FK_E4654464B03A8386");
        $this->addSql("DROP INDEX IDX_E4654464B03A8386 ON geo_country");
        $this->addSql("DROP INDEX IDX_E4654464896DBBDE ON geo_country");
        $this->addSql("ALTER TABLE geo_country DROP updated_by_id, DROP created_by_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_city ADD updated_by_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34896DBBDE FOREIGN KEY (updated_by_id) REFERENCES manager_user (id)");
        $this->addSql("ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34B03A8386 FOREIGN KEY (created_by_id) REFERENCES manager_user (id)");
        $this->addSql("CREATE INDEX IDX_297C2D34B03A8386 ON geo_city (created_by_id)");
        $this->addSql("CREATE INDEX IDX_297C2D34896DBBDE ON geo_city (updated_by_id)");
        $this->addSql("ALTER TABLE geo_country ADD updated_by_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE geo_country ADD CONSTRAINT FK_E4654464896DBBDE FOREIGN KEY (updated_by_id) REFERENCES manager_user (id)");
        $this->addSql("ALTER TABLE geo_country ADD CONSTRAINT FK_E4654464B03A8386 FOREIGN KEY (created_by_id) REFERENCES manager_user (id)");
        $this->addSql("CREATE INDEX IDX_E4654464B03A8386 ON geo_country (created_by_id)");
        $this->addSql("CREATE INDEX IDX_E4654464896DBBDE ON geo_country (updated_by_id)");
        $this->addSql("ALTER TABLE geo_region ADD updated_by_id INT DEFAULT NULL, ADD created_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE geo_region ADD CONSTRAINT FK_A4B3C808896DBBDE FOREIGN KEY (updated_by_id) REFERENCES manager_user (id)");
        $this->addSql("ALTER TABLE geo_region ADD CONSTRAINT FK_A4B3C808B03A8386 FOREIGN KEY (created_by_id) REFERENCES manager_user (id)");
        $this->addSql("CREATE INDEX IDX_A4B3C808B03A8386 ON geo_region (created_by_id)");
        $this->addSql("CREATE INDEX IDX_A4B3C808896DBBDE ON geo_region (updated_by_id)");
    }
}
