<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131209144455 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_region ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL, ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
        $this->addSql("ALTER TABLE geo_region ADD CONSTRAINT FK_A4B3C808B03A8386 FOREIGN KEY (created_by_id) REFERENCES manager_user (id)");
        $this->addSql("ALTER TABLE geo_region ADD CONSTRAINT FK_A4B3C808896DBBDE FOREIGN KEY (updated_by_id) REFERENCES manager_user (id)");
        $this->addSql("CREATE INDEX IDX_A4B3C808B03A8386 ON geo_region (created_by_id)");
        $this->addSql("CREATE INDEX IDX_A4B3C808896DBBDE ON geo_region (updated_by_id)");
        $this->addSql("ALTER TABLE geo_city ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
        $this->addSql("ALTER TABLE geo_country ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
        $this->addSql("ALTER TABLE delivery_city ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
        $this->addSql("ALTER TABLE client ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
        $this->addSql("ALTER TABLE client_deliveryservice DROP FOREIGN KEY FK_7B99D92CE4A54469");
        $this->addSql("DROP INDEX IDX_7B99D92CE4A54469 ON client_deliveryservice");
        $this->addSql("ALTER TABLE client_deliveryservice DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE client_deliveryservice CHANGE deliveryservice_id delivery_service_id INT NOT NULL");
        $this->addSql("ALTER TABLE client_deliveryservice ADD CONSTRAINT FK_7B99D92CF3193EC2 FOREIGN KEY (delivery_service_id) REFERENCES delivery_service (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_7B99D92CF3193EC2 ON client_deliveryservice (delivery_service_id)");
        $this->addSql("ALTER TABLE client_deliveryservice ADD PRIMARY KEY (client_id, delivery_service_id)");
        $this->addSql("ALTER TABLE delivery_service ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
        $this->addSql("ALTER TABLE department ADD created_at DATETIME DEFAULT NULL, ADD updated_at DATETIME DEFAULT NULL, ADD deleted_at DATETIME DEFAULT NULL, DROP createdAt, DROP updatedAt, DROP deletedAt");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE client ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_at, DROP updated_at, DROP deleted_at");
        $this->addSql("ALTER TABLE client_deliveryservice DROP FOREIGN KEY FK_7B99D92CF3193EC2");
        $this->addSql("DROP INDEX IDX_7B99D92CF3193EC2 ON client_deliveryservice");
        $this->addSql("ALTER TABLE client_deliveryservice DROP PRIMARY KEY");
        $this->addSql("ALTER TABLE client_deliveryservice CHANGE delivery_service_id deliveryservice_id INT NOT NULL");
        $this->addSql("ALTER TABLE client_deliveryservice ADD CONSTRAINT FK_7B99D92CE4A54469 FOREIGN KEY (deliveryservice_id) REFERENCES delivery_service (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_7B99D92CE4A54469 ON client_deliveryservice (deliveryservice_id)");
        $this->addSql("ALTER TABLE client_deliveryservice ADD PRIMARY KEY (client_id, deliveryservice_id)");
        $this->addSql("ALTER TABLE delivery_city ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_at, DROP updated_at, DROP deleted_at");
        $this->addSql("ALTER TABLE delivery_service ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_at, DROP updated_at, DROP deleted_at");
        $this->addSql("ALTER TABLE department ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_at, DROP updated_at, DROP deleted_at");
        $this->addSql("ALTER TABLE geo_city ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_at, DROP updated_at, DROP deleted_at");
        $this->addSql("ALTER TABLE geo_country ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_at, DROP updated_at, DROP deleted_at");
        $this->addSql("ALTER TABLE geo_region DROP FOREIGN KEY FK_A4B3C808B03A8386");
        $this->addSql("ALTER TABLE geo_region DROP FOREIGN KEY FK_A4B3C808896DBBDE");
        $this->addSql("DROP INDEX IDX_A4B3C808B03A8386 ON geo_region");
        $this->addSql("DROP INDEX IDX_A4B3C808896DBBDE ON geo_region");
        $this->addSql("ALTER TABLE geo_region ADD createdAt DATETIME DEFAULT NULL, ADD updatedAt DATETIME DEFAULT NULL, ADD deletedAt DATETIME DEFAULT NULL, DROP created_by_id, DROP updated_by_id, DROP created_at, DROP updated_at, DROP deleted_at");
    }
}
