<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130201130848 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE delivery_period DROP FOREIGN KEY FK_DBA9E7402B96F579");
        $this->addSql("ALTER TABLE delivery_period DROP FOREIGN KEY FK_DBA9E740C56731E8");
        $this->addSql("DROP INDEX IDX_DBA9E740C56731E8 ON delivery_period");
        $this->addSql("DROP INDEX IDX_DBA9E7402B96F579 ON delivery_period");
        $this->addSql("ALTER TABLE delivery_period DROP department_to_id, DROP department_from_id");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE delivery_period ADD department_to_id INT DEFAULT NULL, ADD department_from_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE delivery_period ADD CONSTRAINT FK_DBA9E7402B96F579 FOREIGN KEY (department_to_id) REFERENCES department (id)");
        $this->addSql("ALTER TABLE delivery_period ADD CONSTRAINT FK_DBA9E740C56731E8 FOREIGN KEY (department_from_id) REFERENCES department (id)");
        $this->addSql("CREATE INDEX IDX_DBA9E740C56731E8 ON delivery_period (department_from_id)");
        $this->addSql("CREATE INDEX IDX_DBA9E7402B96F579 ON delivery_period (department_to_id)");
    }
}
