<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121120103704 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE manager_user ADD client_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE manager_user ADD CONSTRAINT FK_8B9A743019EB6921 FOREIGN KEY (client_id) REFERENCES client (id)");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_8B9A743019EB6921 ON manager_user (client_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE manager_user DROP FOREIGN KEY FK_8B9A743019EB6921");
        $this->addSql("DROP INDEX UNIQ_8B9A743019EB6921 ON manager_user");
        $this->addSql("ALTER TABLE manager_user DROP client_id");
    }
}
