<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131211135825 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE client_delivery (client_id INT NOT NULL, delivery_id INT NOT NULL, INDEX IDX_1967DCD519EB6921 (client_id), INDEX IDX_1967DCD512136921 (delivery_id), PRIMARY KEY(client_id, delivery_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE warehouse (id INT AUTO_INCREMENT NOT NULL, delivery_city_id INT DEFAULT NULL, delivery_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COMMENT 'Название отделения', address VARCHAR(255) NOT NULL COMMENT 'Адрес отделения', phone VARCHAR(255) NOT NULL COMMENT 'Телефон отделения', latitude NUMERIC(13, 8) NOT NULL COMMENT 'Широта', longitude NUMERIC(13, 8) NOT NULL COMMENT 'Долгота', ware_id_city VARCHAR(10) DEFAULT NULL, ware_id VARCHAR(10) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ECB38BFC81B2DD71 (delivery_city_id), INDEX IDX_ECB38BFC12136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE client_delivery ADD CONSTRAINT FK_1967DCD519EB6921 FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE client_delivery ADD CONSTRAINT FK_1967DCD512136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFC81B2DD71 FOREIGN KEY (delivery_city_id) REFERENCES delivery_city (id)");
        $this->addSql("ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFC12136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE client_delivery");
        $this->addSql("DROP TABLE warehouse");
    }
}
