<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131211184025 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE delivery_cities (id INT AUTO_INCREMENT NOT NULL, geo_city_id INT DEFAULT NULL, delivery_id INT DEFAULT NULL, city_code VARCHAR(100) NOT NULL COMMENT 'ID города в ТК', name VARCHAR(255) NOT NULL COMMENT 'Название города', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_C74C48E53CBAEFAD (geo_city_id), INDEX IDX_C74C48E512136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE delivery_cities ADD CONSTRAINT FK_C74C48E53CBAEFAD FOREIGN KEY (geo_city_id) REFERENCES geo_city (id)");
        $this->addSql("ALTER TABLE delivery_cities ADD CONSTRAINT FK_C74C48E512136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id)");
        $this->addSql("ALTER TABLE delivery DROP settings, DROP registration_cost, DROP commission, DROP min_commission");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE delivery_cities");
        $this->addSql("ALTER TABLE delivery ADD settings LONGTEXT NOT NULL COMMENT 'Массив настроек(DC2Type:array)', ADD registration_cost INT DEFAULT NULL, ADD commission NUMERIC(10, 2) DEFAULT NULL, ADD min_commission NUMERIC(10, 2) DEFAULT NULL");
    }
}
