<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131209153254 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_country ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE geo_country ADD CONSTRAINT FK_E4654464B03A8386 FOREIGN KEY (created_by_id) REFERENCES manager_user (id)");
        $this->addSql("ALTER TABLE geo_country ADD CONSTRAINT FK_E4654464896DBBDE FOREIGN KEY (updated_by_id) REFERENCES manager_user (id)");
        $this->addSql("CREATE INDEX IDX_E4654464B03A8386 ON geo_country (created_by_id)");
        $this->addSql("CREATE INDEX IDX_E4654464896DBBDE ON geo_country (updated_by_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_country DROP FOREIGN KEY FK_E4654464B03A8386");
        $this->addSql("ALTER TABLE geo_country DROP FOREIGN KEY FK_E4654464896DBBDE");
        $this->addSql("DROP INDEX IDX_E4654464B03A8386 ON geo_country");
        $this->addSql("DROP INDEX IDX_E4654464896DBBDE ON geo_country");
        $this->addSql("ALTER TABLE geo_country DROP created_by_id, DROP updated_by_id");
    }
}
