<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131213183417 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE delivery_cities (id INT AUTO_INCREMENT NOT NULL, geo_city_id INT DEFAULT NULL, delivery_id INT DEFAULT NULL, city_code VARCHAR(100) DEFAULT NULL COMMENT 'ID города в ТК', name VARCHAR(255) NOT NULL COMMENT 'Название города', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_C74C48E53CBAEFAD (geo_city_id), INDEX IDX_C74C48E512136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE delivery_warehouses (id INT AUTO_INCREMENT NOT NULL, delivery_id INT DEFAULT NULL, city_id INT DEFAULT NULL, warehouse_code VARCHAR(100) DEFAULT NULL COMMENT 'ID склада в ТК', number VARCHAR(25) DEFAULT NULL COMMENT 'Номер склада в городе', name VARCHAR(255) NOT NULL COMMENT 'Название отделения', address VARCHAR(255) NOT NULL COMMENT 'Адрес отделения', phone VARCHAR(255) NOT NULL COMMENT 'Телефон отделения', latitude NUMERIC(13, 8) NOT NULL COMMENT 'Широта', longitude NUMERIC(13, 8) NOT NULL COMMENT 'Долгота', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_B1AC559312136921 (delivery_id), INDEX IDX_B1AC55938BAC62AF (city_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE delivery_cities ADD CONSTRAINT FK_C74C48E53CBAEFAD FOREIGN KEY (geo_city_id) REFERENCES geo_city (id)");
        $this->addSql("ALTER TABLE delivery_cities ADD CONSTRAINT FK_C74C48E512136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id)");
        $this->addSql("ALTER TABLE delivery_warehouses ADD CONSTRAINT FK_B1AC559312136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id)");
        $this->addSql("ALTER TABLE delivery_warehouses ADD CONSTRAINT FK_B1AC55938BAC62AF FOREIGN KEY (city_id) REFERENCES delivery_cities (id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE delivery_warehouses DROP FOREIGN KEY FK_B1AC55938BAC62AF");
        $this->addSql("DROP TABLE delivery_cities");
        $this->addSql("DROP TABLE delivery_warehouses");
    }
}
