<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131211191824 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE delivery_warehouses (id INT AUTO_INCREMENT NOT NULL, city_id INT DEFAULT NULL, delivery_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COMMENT 'Название отделения', address VARCHAR(255) NOT NULL COMMENT 'Адрес отделения', phone VARCHAR(255) NOT NULL COMMENT 'Телефон отделения', latitude NUMERIC(13, 8) NOT NULL COMMENT 'Широта', longitude NUMERIC(13, 8) NOT NULL COMMENT 'Долгота', created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_B1AC55938BAC62AF (city_id), INDEX IDX_B1AC559312136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE delivery_warehouses ADD CONSTRAINT FK_B1AC55938BAC62AF FOREIGN KEY (city_id) REFERENCES delivery_cities (id)");
        $this->addSql("ALTER TABLE delivery_warehouses ADD CONSTRAINT FK_B1AC559312136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id)");
        $this->addSql("DROP TABLE warehouse");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE warehouse (id INT AUTO_INCREMENT NOT NULL, delivery_id INT DEFAULT NULL, delivery_city_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL COMMENT 'Название отделения', address VARCHAR(255) NOT NULL COMMENT 'Адрес отделения', phone VARCHAR(255) NOT NULL COMMENT 'Телефон отделения', latitude NUMERIC(13, 8) NOT NULL COMMENT 'Широта', longitude NUMERIC(13, 8) NOT NULL COMMENT 'Долгота', ware_id_city VARCHAR(10) DEFAULT NULL, ware_id VARCHAR(10) NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_ECB38BFC81B2DD71 (delivery_city_id), INDEX IDX_ECB38BFC12136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFC12136921 FOREIGN KEY (delivery_id) REFERENCES delivery (id)");
        $this->addSql("ALTER TABLE warehouse ADD CONSTRAINT FK_ECB38BFC81B2DD71 FOREIGN KEY (delivery_city_id) REFERENCES delivery_city (id)");
        $this->addSql("DROP TABLE delivery_warehouses");
    }
}
