<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20121105123440 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE geo_country (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, createdAt DATETIME DEFAULT NULL, updatedAt DATETIME DEFAULT NULL, deletedAt DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE geo_region ADD country_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE geo_region ADD CONSTRAINT FK_A4B3C808F92F3E70 FOREIGN KEY (country_id) REFERENCES geo_country (id)");
        $this->addSql("CREATE INDEX IDX_A4B3C808F92F3E70 ON geo_region (country_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_region DROP FOREIGN KEY FK_A4B3C808F92F3E70");
        $this->addSql("DROP TABLE geo_country");
        $this->addSql("DROP INDEX IDX_A4B3C808F92F3E70 ON geo_region");
        $this->addSql("ALTER TABLE geo_region DROP country_id");
    }
}
