<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20131209162827 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_city ADD created_by_id INT DEFAULT NULL, ADD updated_by_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34B03A8386 FOREIGN KEY (created_by_id) REFERENCES manager_user (id)");
        $this->addSql("ALTER TABLE geo_city ADD CONSTRAINT FK_297C2D34896DBBDE FOREIGN KEY (updated_by_id) REFERENCES manager_user (id)");
        $this->addSql("CREATE INDEX IDX_297C2D34B03A8386 ON geo_city (created_by_id)");
        $this->addSql("CREATE INDEX IDX_297C2D34896DBBDE ON geo_city (updated_by_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34B03A8386");
        $this->addSql("ALTER TABLE geo_city DROP FOREIGN KEY FK_297C2D34896DBBDE");
        $this->addSql("DROP INDEX IDX_297C2D34B03A8386 ON geo_city");
        $this->addSql("DROP INDEX IDX_297C2D34896DBBDE ON geo_city");
        $this->addSql("ALTER TABLE geo_city DROP created_by_id, DROP updated_by_id");
    }
}
