generator: admingenerator.generator.doctrine
params:
    model: Nitra\GeoBundle\Entity\City
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: GeoBundle
    pk_requirement: ~
    fields:
        region:     { label: "Регион", addFormOptions: { required: true } }
        name:       { label: "Город",  addFormOptions: { required: true } }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Эталон - список городов"
            display:        [ region, name ]
            sort:           [ name, ASC ]
            max_per_page:   50
            actions:
                new: ~
            object_actions:
                edit: ~
            
    filters:
        params:
            display:    [ region, name ]
            fields:
                region: { addFormOptions: { required: false } }
                name:   { addFormOptions: { required: false } }
            
    new:
        params:
            title:      "Эталон - добавить новый город"
            display:    [ region, name ]
            actions:
                save:   ~
                save-and-list: ~
                list:   ~
                
    edit:
        params:
            title:      "Эталон - редактировать город \"%object%\"|{ %object%: City.name }|"
            display:    [ region, name ]
            actions:
                save:   ~
                save-and-list: ~
                list:   ~
                
    show:
        params:
            title:      "Эталон - просмотр города \"%object%\"|{ %object%: City.name }|"
            display:    ~
            actions:
                list:   ~
                new:    ~
                
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
