generator: admingenerator.generator.doctrine
params:
    model: Nitra\GeoBundle\Entity\City
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: GeoBundle
    pk_requirement: ~
    fields:
        region:         { label: "Регион" }
        name:           { label: "Город" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Список городов"
            display:        [ country, region, name ]
            sort:           [ name, ASC ]
            max_per_page:   50
            actions:
                new:    ~
            object_actions:
                edit:   ~
                delete: ~
    filters:
        params:
            display:    [ region, name ]
    new:
        params:
            title:      "Добавить новый город"
            display:    [ region, name ]
            actions:
                save:   ~
                list:   ~
    edit:
        params:
            title:      "Редактировать город \"%object%\"|{ %object%: City.name }|"
            display:    [ region, name ]
            actions:
                save:   ~
                list:   ~
    show:
        params:
            title:      "Просмотр города \"%object%\"|{ %object%: City.name }|"
            display:    ~
            actions:
                list:   ~
                new:    ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
