generator: admingenerator.generator.doctrine
params:
    model: Nitra\GeoBundle\Entity\Country
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: GeoBundle
    pk_requirement: ~
    fields:
        name:       { label: "Страна" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:      "Эталон - список стран"
            display:    [ name ]
            sort:       [ name, ASC ]
            actions:
                new: ~
            object_actions:
                edit:   ~
                delete: []
    filters:
        params:
            display:    [ name ]
    new:
        params:
            title:      "Эталон - добавить новую страну"
            display:    [ name ]
            actions:
                save:   ~
                list:   ~
    edit:
        params:
            title:      "Эталон - редактировать страну \"%object%\"|{ %object%: Country.name }|"
            display:    [ name ]
            actions:
                save:   ~
                list:   ~
    show:
        params:
            title:      "Эталон - просмотр страны \"%object%\"|{ %object%: Country.name }|"
            display:    [ name ]
            actions:
                list:   ~
                new:    ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
