generator:                  admingenerator.generator.doctrine
params:
  model:                    Nitra\GeoBundle\Entity\Region
  namespace_prefix:         Nitra
  bundle_name:              GeoBundle
  fields:
    name:
      label:                Название региона

builders:
  list:
    params:
      title:                 Список регионов
      display:               [ name ]
      sort:                  [ name, ASC ]
      max_per_page:          50
      actions:
        new:                 ~
      object_actions:
        edit:                ~
        delete:              ~
  filters:
    params:
      display:               [ name ]
  new:
    params:
      title:                 Добавление нового региона
      display:               [ name ]
      actions:
        list:                ~
  edit:
    params:
      title:                 Редактирование региона "{{ Region.name }}"
      display:               [ name ]
      actions:
        list:                ~
  delete:                    ~
