generator: admingenerator.generator.doctrine
params:
    model: Nitra\GeoBundle\Entity\Region
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: GeoBundle
    pk_requirement: ~
    fields:
        country:    { label: "Страна", addFormOptions: { required: true } }
        regionId:   { label: "ID региона", dbType: integer, filter_on: id }
        name:       { label: "Регион", addFormOptions: { required: true } }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Эталон - список регионов"
            display:        [ id, country, name ]
            sort:           [ name, ASC ]
            max_per_page:   50
            actions:
                new: ~
            object_actions:
                edit: ~
            
    filters:
        params:
            display:        [ country, regionId, name ]
            fields:
                country:    { addFormOptions: { required: false } }
                name:       { addFormOptions: { required: false } }
            
    new:
        params:
            title:      "Эталон - добавить новый регион"
            display:    [ country, name ]
            actions:
                save:   ~
                save-and-list: ~
                list:   ~
                
    edit:
        params:
            title:      "Эталон - редактировать регион \"%object%\"|{ %object%: Region.name }|"
            display:    [ country, name ]
            actions:
                save:   ~
                save-and-list: ~
                list:   ~
                
    show:
        params:
            title:      "Эталон - просмотр региона \"%object%\"|{ %object%: Region.name }|"
            display:    [ name ]
            actions:
                list:   ~
                new:    ~
                
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
