generator: admingenerator.generator.doctrine
params:
    model: Nitra\GeoBundle\Entity\Region
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: GeoBundle
    pk_requirement: ~
    fields:
        country:    { label: "Страна" }
        name:       { label: "Регион" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Эталон - список регионов"
            display:        [ id, country, name ]
            sort:           [ name, ASC ]
            max_per_page:   50
            actions:        []
            object_actions: []
            
    filters:
        params:
            display:    [ country, name ]
            
    new:
        params:
            title:      "Эталон - добавить новый регион"
            display:    [ name ]
            actions:
                save:   ~
                list:   ~
                
    edit:
        params:
            title:      "Эталон - редактировать регион \"%object%\"|{ %object%: Region.name }|"
            display:    ~
            actions:
                save:   ~
                list:   ~
                
    show:
        params:
            title:      "Эталон - просмотр региона \"%object%\"|{ %object%: Region.name }|"
            display:    [ name ]
            actions:
                list:   ~
                new:    ~
                
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
