
#NitraGeoBundleCommon:
#    resource: "@NitraGeoBundle/Controller/City/"
#    type:     annotation
#    prefix:   /geo
#
#

NitraGeoBundleCity:
    resource: "@NitraGeoBundle/Controller/City/"
    type:     admingenerator
    prefix:   /geo/city

NitraGeoBundleRegion:
    resource: "@NitraGeoBundle/Controller/Region/"
    type:     admingenerator
    prefix:   /geo/region
    
NitraGeoBundleCountry:
    resource: "@NitraGeoBundle/Controller/Country/"
    type:     admingenerator
    prefix:   /geo/country
    
NitraGeoBundleFixtures:
    resource: "@NitraGeoBundle/Controller/FixturesController.php"
    type:     annotation
    prefix:   /geo-fixtures

    