
# Справочник эталонные города 
NitraGeoBundleCity:
    resource: "@NitraGeoBundle/Controller/City/"
    type:     admingenerator
    prefix:   /geo-city

# Справочник эталонные регионы
NitraGeoBundleRegion:
    resource: "@NitraGeoBundle/Controller/Region/"
    type:     admingenerator
    prefix:   /geo-region
    
# Справочник эталонные страны
NitraGeoBundleCountry:
    resource: "@NitraGeoBundle/Controller/Country/"
    type:     admingenerator
    prefix:   /geo-country
    
# формирование фикстур по существующим эталонным данным
NitraGeoBundleFixtures:
    resource: "@NitraGeoBundle/Controller/FixturesController.php"
    type:     annotation
    prefix:   /geo-fixtures

    