NitraGeoBundleCity:
    resource: "@NitraGeoBundle/Controller/City/"
    type:     admingenerator
    prefix:   /city

NitraGeoBundleRegion:
    resource: "@NitraGeoBundle/Controller/Region/"
    type:     admingenerator
    prefix:   /region
    
NitraGeoBundleCountry:
    resource: "@NitraGeoBundle/Controller/Country/"
    type:     admingenerator
    prefix:   /country
