generator: admingenerator.generator.doctrine
params:
    model: Nitra\ManagerBundle\Entity\Group
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: ManagerBundle
    pk_requirement: ~
    fields:
        name:   { label: "Название группы" }
        roles:  { label: "Привелегии группы" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:      "Список групп"
            display:    [ name, roles ]
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:    [ name, roles ]
    new:
        params:
            title:      "Добавить новую группу"
            display:    [ name, roles ]
            actions:
                save:   ~
                list:   ~
    edit:
        params:
            title:      "Редактировать группу \"%object%\"|{ %object%: Group.name }|"
            display:    [ name, roles ]
            actions:
                save:   ~
                list:   ~
    show:
        params:
            title:      "Просмотр группы \"%object%\"|{ %object%: Group.name }|"
            display:    ~
            actions:
                list:   ~
                new:    ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
