generator: admingenerator.generator.doctrine
params:
    model: Nitra\ManagerBundle\Entity\Manager
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: ManagerBundle
    pk_requirement: ~
    fields: ~
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:      "Список менеджеров"
            display:    [ username, email, enabled, lastLogin, locked, expired, client, groups ]
            actions:
                new:    ~
            object_actions:
                edit:   ~
                delete: ~
    filters:
        params:
            display:    [ username, email ]
    new:
        params:
            title:      "Добавить нового менеджера"
            display:    [ username, email, enabled, locked,  password, client ]
            actions:
                save:   ~
                list:   ~
    edit:
        params:
            title:      "Редактировать менеджера \"%object%\"|{ %object%: Manager.username }|"
            display:    [ username, email, enabled, locked,  password, client ]
            actions:
                save:   ~
                list:   ~
    show:
        params:
            title:      "Просмотр менеджера \"%object%\"|{ %object%: Manager.username }|"
            display: ~
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
