generator: admingenerator.generator.doctrine
params:
    model: Nitra\ManagerBundle\Entity\Manager
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: ManagerBundle
    pk_requirement: ~
    fields:
        username:   { label: "Логин" }
        email:      { label: "Емейл" }
        password:   { label: "Пароль", formType: password }
        enabled:    { label: "Включено?" }
        lastLogin:  { label: "Последний вход" }
        locked:     { label: "Заблокировано?"}
        expired:    { label: "Срок действия закончился?" }
        
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Список менеджеров"
            display:        [ username, email, enabled, lastLogin ]
            actions:        []
            object_actions: []
                
    filters:
        params:
            display:    [ username, email, locked ]
            
    new:
        params:
            title:      "Добавить нового менеджера"
            display:    [ username, email, enabled, password ]
            actions:
                save:   ~
                list:   ~
                
    edit:
        params:
            title:      "Редактировать менеджера \"%object%\"|{ %object%: Manager.username }|"
            display:    [ username, email, enabled, password ]
            actions:
                save:   ~
                list:   ~
                
    show:
        params:
            title:      "Просмотр менеджера \"%object%\"|{ %object%: Manager.username }|"
            display: ~
            actions:
                list: ~
                new: ~
                
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
