generator:                        admingenerator.generator.doctrine
params:
  model:                          Nitra\ManagerBundle\Entity\Manager
  namespace_prefix:               Nitra
  bundle_name:                    ManagerBundle
  fields:
    username:
      label:                      Логин
    email:
      label:                      Емейл
    enabled:
      label:                      Включено?
    lastLogin:
      label:                      Последний вход
    locked:
      label:                      Заблокировано?
    expired:
      label:                      Срок действия закончился?
    roles_text:
      label:                      Привилегии
    client:
      label:                      Клиент
    groups:
      label:                      Группы

builders:
  list:
    params:
      title:                      Список менеджеров
      display:                    [ username, email, enabled, lastLogin, locked, expired, client, groups ]
      actions:
        new:                      ~
      object_actions:
        edit:                     ~
        delete:                   ~
  filters:
    params:
      display:                    [ username, email ]
  new:
    params:
      title:                      Добавление нового менеджера
      display:                    [ username, email, enabled, locked,  password, client, groups ]
      actions:
        list:                     ~
  edit:
    params:
      title:                      Редактирование менеджера "{{ Manager }}"
      display:                    [ username, email, enabled, locked, password, client, groups ]
      actions:
        list:                     ~
  delete:                         ~
