generator: admingenerator.generator.doctrine
params:
  model: Nitra\ManagerBundle\Entity\Role
  namespace_prefix: Nitra
  bundle_name: ManagerBundle
  fields: 
    name:
      label:   Название привилегии
    description:
      label:    Описание привилегии

builders:
  list:
    params:
      title: Список привелегий
      display: [ name, description ]
      actions:
        new: ~
      object_actions:
        edit: ~
        delete: ~
  filters:
    params:
      display: [ name, description ]
  new:
    params:
      title:  Новая группа
      display: [ name, description ]
      actions:
        list: ~
  edit:
    params:
      title: Редактирование привелегии "%Role%"|{ %Role%: Role.name }|
      display: [ name, description ]
      actions:
        list: ~
  delete: ~
