generator: admingenerator.generator.doctrine
params:
    model: Nitra\ManagerBundle\Entity\Role
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: ManagerBundle
    pk_requirement: ~
    fields:
        name:           { label: "Название привилегии" }
        description:    { label: "Описание привилегии" }
        
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:      "Список привелегий"
            display:    [ name, description ]
            actions:        []
            object_actions: []
                
    filters:
        params:
            display:    []
    new:
        params:
            title:      "Добавить новую привелегию"
            display:    [ name, description ]
            actions:
                save:   ~
                list:   ~
    edit:
        params:
            title:      "Редактировать привелегию \"%object%\"|{ %object%: Role.name }|"
            display:    [ name, description ]
            actions:
                save:   ~
                list:   ~
    show:
        params:
            title:      "Просмотр привелегии \"%object%\"|{ %object%: Role.name }|"
            display:    ~
            actions:
                list:   ~
                new:    ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
