generator: admingenerator.generator.doctrine
params:
  model: Nitra\DeliveryCostBundle\Entity\NovaposhtaTarify
  namespace_prefix: Nitra
  bundle_name: DeliveryCostBundle
  fields: ~

builders:
  list:
    params:
      title: Справочник по ТК "Новая почта"
      display: ~
      object_actions:
        edit: 
          params:
            actions:
              list: ~
  filters:
    params:
      display: ~
  
  edit:
    params:
      title: "You're editing the object "
      display: ~
      actions:
        list: ~
  show:
    params:
      title: "You're viewing the object "
      display: ~
      actions:
        list: ~
  delete: ~
