generator: admingenerator.generator.doctrine
params:
    model: Nitra\DeliveryBundle\Entity\City
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: DeliveryBundle
    pk_requirement: ~
    fields:
        delivery:   { label: "Транспортная компания" }
        geoCity:    { label: "Эталон город" }
        geoCityId:  { label: "ID эталон город" }
        name:       { label: "Название города" }
        nameTk:     { label: "Название города в ТК" }
        updatedAt:  { label: "Обновлено" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Список городов ТК"
            display:        [ delivery, geoCityId, geoCity, name, nameTk, updatedAt ]
            sort:           [ name, ASC ]
            max_per_page:   100
            actions:        []
            object_actions:
                edit: ~
#                delete: ~
            
                
    filters:
        params:
            display:    [ delivery, name, nameTk ]
            
    new:
        params:
            title:      "Добавить новый город ТК"
            display:    [ delivery, geoCity, name ]
            actions:
                save: ~
                save-and-list: ~
                list: ~
                
    edit:
        params:
            title:      "Редактировать город ТК \"%object%\"|{ %object%: City.name }|"
            display:    [ delivery, geoCity, name ]
            actions:
                save: ~
                save-and-list: ~
                list: ~
                
    show:
        params:
            title:      "Просмотр города ТК \"%object%\"|{ %object%: City.name }|"
            display: ~
            actions:
                list: ~
                new: ~
                
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
