generator: admingenerator.generator.doctrine
params:
    model: Nitra\DeliveryBundle\Entity\Client
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: DeliveryBundle
    pk_requirement: ~
    fields: 
        name:       { label: "Название клиента" }
        deliveries: { label: "ТК" }
        token:      { label: "Токен" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Список клиентов"
            display:        [ name, token, deliveries ]
            sort:           [ name, ASC ]
            max_per_page:   100
            actions:
                new: ~
            object_actions:
                # NewToken:   { label: "Сгенерировать новый токен" }
                edit: ~
                delete: ~
                
    filters:
        params:
            display:        [ name ]
            
    new:
        params:
            title:          "Добавить нового клиента"
            display:        [ name, token, deliveries ]
            max_per_page:   100
            actions:
                save: ~
                save-and-list: ~
                list: ~
                
    edit:
        params:
            title:      "Редактировать клиента \"%object%\"|{ %object%: Client.name }|"
            display:    [ name, token, deliveries ]
            actions:
                save: ~
                save-and-list: ~
                list: ~
                
    show:
        params:
            title:      "Просмотр клиента \"%object%\"|{ %object%: Client.name }|"
            display:    ~
            actions:
                list: ~
                new: ~
                
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
