generator: admingenerator.generator.doctrine
params:
    model: Nitra\DeliveryBundle\Entity\Client
    namespace_prefix: Nitra
    concurrency_lock: ~
    bundle_name: DeliveryBundle
    pk_requirement: ~
    fields: 
        name:       { label: "Название клиента" }
        user:       { label: "Менеджер" }
        deliveries: { label: "ТК" }
    object_actions:
        delete: ~
    batch_actions:
        delete: ~
builders:
    list:
        params:
            title:          "Список клиентов"
            display:        [ name, user, deliveries ]
            max_per_page:   100
            actions:
                new: ~
            object_actions:
                edit: ~
                delete: ~
    filters:
        params:
            display:        [ name ]
    new:
        params:
            title:          "Добавить нового клиента"
            display:        [ name, user, deliveries ]
            sort:           [ name, ASC ]
            max_per_page:   100
            actions:
                save: ~
                save-and-list: ~
                list: ~
    edit:
        params:
            title:      "Редактировать клиента \"%object%\"|{ %object%: Client.name }|"
            display:    [ name, user, deliveries ]
            actions:
                save: ~
                save-and-list: ~
                list: ~
    show:
        params:
            title:      "Просмотр города \"%object%\"|{ %object%: Client.name }|"
            display:    [ name, user, deliveries ]
            actions:
                list: ~
                new: ~
    actions:
        params:
            object_actions:
                delete: ~
            batch_actions:
                delete: ~
